# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: List all tasks
    silent: true
    cmds:
      - task --list-all

  start:
    desc: Start production server
    silent: true
    deps:
      - env
      - build
    cmd: bun start

  build:
    desc: Builds the app
    sources:
      - ./src/**/*
      - ./tailwind.config.ts
      - ./next.config.ts
      - ./tsconfig.json
      - ./postcss.config.mjs
    status:
      - test -d .next # triggers if .next does not exists
    deps:
      - install
    cmd: bun run build # 'bun build' triggers the bun bundler

  dev:
    desc: Runs next dev server
    deps:
      - env
      - install
    cmd: bun dev

  db:
    desc: Runs convex sync cli
    deps:
      - env
      - install
    cmd: bun db

  format:
    desc: Runs prettier cli
    deps:
      - install
    cmd: bunx prettier . --write

  lint:
    desc: Runs 'next lint'
    silent: true
    deps:
      - install
    cmd: bun lint

  install:
    desc: Install depencencies
    status:
      - test -d node_modules # triggers if node_modules does not exists
    sources:
      - package.json
      - bun.lock
    cmds:
      - bun install

  env:
    desc: Creates .env.local variables with empty values
    status:
      - test -f .env.local
    cmd: cp env.example .env.local

  reset:
    desc: Remove 'node_modules', '.next' and '.task' directories
    silent: true
    cmds:
      - rm -rf node_modules
      - rm -rf .next
      - rm -rf .task

  clean:
    desc: Remove '.next' directory
    silent: true
    cmds:
      - rm -rf .next
